import {
  // Main Icons
  LayoutDashboard,
  CheckSquare,
  Settings,
  Clock,
  FileText,
  Users,
  UserCog,
  Building2,
  FolderKanban,
  Briefcase,
  Calendar,
  FileCheck,
  UserPlus,
  TrendingUp,
  Award,
  PieChart,
  Target,
  Download,
  Bell,
  MessageSquare,
  Mail,
  GitBranch,
  Activity,
  Zap,
  Shield,
  BarChart3,
  CreditCard,
  HelpCircle,
  LifeBuoy,
  BookOpen,
  UserCheck,
  UserX,
  UserMinus,
  DollarSign,
  Key,
  Database,
  Globe,
  Rocket,
  Star,
  Eye,
  Edit2,
  Trash2,
  Plus,
  Search,
  Filter,
  RefreshCw,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronDown,
  Menu,
  X,
  Home,
  LogOut,
  User as UserIcon,
  Lock,
  Unlock,
  CheckCircle,
  AlertCircle,
  Info,
  Loader2,
  PlusCircle,
  MinusCircle,
  XCircle,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  CalendarDays,
  Clock8,
  Timer,
  AlarmClock,
  CheckCheck,
  AlertTriangle,
  Megaphone,
  Send,
  Inbox,
  Archive,
  Copy,
  Link2,
  ExternalLink,
  Folder,
  FolderOpen,
  FolderPlus,
  File,
  FileSpreadsheet,
  FileImage,
  FileVideo,
  FileAudio,
  FileArchive,
  FileCode,
  FileJson,
  Image,
  Video,
  Music,
  Code,
  Terminal,
  Command,
  Monitor,
  Smartphone,
  Tablet,
  Laptop,
  Watch,
  Camera,
  Video as VideoIcon,
  Mic,
  Headphones,
  Speaker,
  Printer,
  Scan,
  QrCode,
  Wifi,
  Bluetooth,
  Usb,
  Plug,
  Power,
  Battery,
  Cpu,
  HardDrive,
  Server,
  Cloud,
  Database as DatabaseIcon,
  Network,
  WifiOff,
  BluetoothOff,
  BatteryCharging,
  BatteryFull,
  BatteryLow,
  BatteryMedium,
  BatteryWarning,
  Signal,
  SignalLow,
  SignalMedium,
  SignalHigh,
  Volume1,
  Volume2,
  VolumeX,
  MicOff,
  CameraOff,
  VideoOff,
  WifiOff as WifiOffIcon,
  BluetoothConnected,
  BluetoothOff as BluetoothOffIcon,
  Usb as UsbIcon,
  Plug as PlugIcon,
  Power as PowerIcon,
  Battery as BatteryIcon,
  Cpu as CpuIcon,
  HardDrive as HardDriveIcon,
  Server as ServerIcon,
  Cloud as CloudIcon,
  Database as DatabaseIcon2,
  Network as NetworkIcon,
  Globe as GlobeIcon,
  Map,
  MapPin,
  Compass,
  Navigation,
  Navigation2,
  Home as HomeIcon,
  Building,
  Factory,
  Warehouse,
  Store,
  Hospital,
  School,
  University,
  Library,
  Coffee,
  Beer,
  Wine,
  Cake,
  Pizza,
  Burger,
  Apple,
  Leaf,
  Tree,
  Flower,
  Sun,
  Moon,
  CloudRain,
  CloudSnow,
  CloudLightning,
  CloudFog,
  Wind,
  Tornado,
  Waves,
  Droplets,
  Thermometer,
  Snowflake,
  Flame,
  Fire,
  Car,
  Bus,
  Train,
  Plane,
  Ship,
  Bike,
  Run,
  Walk,
  Move,
  RotateCw,
  RotateCcw,
  ZoomIn,
  ZoomOut,
  Maximize,
  Minimize,
  Maximize2,
  Minimize2,
  Crop,
  Scissors,
  Ruler,
  Weight,
  Scale,
  Gauge,
  Heart,
  HeartPulse,
  Brain,
  Bone,
  Tooth,
  Stethoscope,
  Syringe,
  Pill,
  Ambulance,
  Bandage,
  Microscope,
  TestTube,
  Flask,
  Beaker,
  Atom,
  Dna,
  Bug,
  BugOff,
  Spider,
  Bee,
  Butterfly,
  Fish,
  Bird,
  Cat,
  Dog,
  Rabbit,
  Turtle,
  Fox,
  Lion,
  Tiger,
  Elephant,
  Monkey,
  Panda,
  Penguin,
  Dolphin,
  Whale,
  Shark,
  Octopus,
  Crab,
  Snail,
  Frog,
  Lizard,
  Snake,
  Dragon,
  Ghost,
  Skull,
  Pumpkin,
  Hat,
  Glasses,
  Sunglasses,
  Mask,
  Helmet,
  ShieldCheck,
  ShieldAlert,
  ShieldX,
  ShieldOff,
  LockKeyhole,
  LockOpen,
  UnlockKeyhole,
  KeyRound,
  KeySquare,
  Badge,
  BadgeCheck,
  BadgeAlert,
  BadgeX,
  BadgeOff,
  Verified,
  CheckVerified,
  AlertOctagon,
  Flag,
  FlagTriangleRight,
  FlagOff,
  Trophy,
  Medal,
  Gem,
  Diamond,
  Sparkles,
  Crown,
  Award as AwardIcon,
  TrendingUp as TrendingUpIcon,
  TrendingDown,
  TrendingFlat,
  LineChart,
  BarChart,
  BarChartHorizontal,
  PieChart as PieChartIcon,
  AreaChart,
  ScatterChart,
  Radar,
  Activity as ActivityIcon,
  Pulse,
  Heartbeat,
  Thermometer as ThermometerIcon,
  Droplet,
  Wind as WindIcon,
  Waves as WavesIcon,
  Zap as ZapIcon,
  Bolt,
  Flashlight,
  Lightbulb,
  LightbulbOff,
  Sun as SunIcon,
  Moon as MoonIcon,
  Sunrise,
  Sunset,
  Cloudy,
  PartlyCloudy,
  CloudDrizzle,
  CloudFog as CloudFogIcon,
  CloudHail,
  CloudRain as CloudRainIcon,
  CloudSnow as CloudSnowIcon,
  CloudSun,
  CloudMoon,
  CloudLightning as CloudLightningIcon,
  CloudWind,
  Cloudy as CloudyIcon,
  Haze,
  Humidity,
  Pressure,
  UV,
  Visibility,
  Compass as CompassIcon,
  Map as MapIcon,
  MapPin as MapPinIcon,
  Navigation as NavigationIcon,
  Navigation2 as Navigation2Icon,
  Target as TargetIcon,
  Crosshair,
  Aim,
  Bullseye,
  Ruler as RulerIcon,
  Scale as ScaleIcon,
  Weight as WeightIcon,
  Gauge as GaugeIcon,
  Speedometer,
  Tachometer,
  Meter,
  ThermometerSnowflake,
  ThermometerSun,
  Sprout,
  Seed,
  Tree as TreeIcon,
  Flower as FlowerIcon,
  Leaf as LeafIcon,
  Apple as AppleIcon,
  Cherry,
  Grape,
  Orange,
  Watermelon,
  Carrot,
  Broccoli,
  Corn,
  Wheat,
  Egg as EggIcon,
  Milk,
  Cheese,
  Bread,
  Croissant,
  Cookie,
  Donut,
  Cupcake,
  IceCream,
  IceCream2,
  Cake as CakeIcon,
  Pie,
  Pizza as PizzaIcon,
  Burger as BurgerIcon,
  Sandwich,
  Hotdog,
  Taco,
  Burrito,
  Ramen,
  Sushi,
  Rice,
  Noodles,
  Soup,
  Salad,
  EggFried,
  Bacon,
  Chicken,
  Meat,
  Fish as FishIcon,
  Shrimp,
  Lobster,
  Crab as CrabIcon,
  Coffee as CoffeeIcon,
  Tea,
  Soda,
  Beer as BeerIcon,
  Wine as WineIcon,
  Cocktail,
  Champagne,
  Whiskey,
  Vodka,
  Rum,
  Gin,
  Tequila,
  Brandy,
  Liqueur,
  Vermouth,
  Sherry,
  Port,
  Sake,
  Cider,
  Kombucha,
  Juice,
  Water as WaterIcon,
  SparklingWater,
  EnergyDrink,
  SportsDrink,
  ProteinShake,
  Smoothie,
  Milkshake,
  Blush,
  Flushed,
  Grin,
  Happy,
  Sad,
  Sleepy,
  Tired,
  Cool,
  Hot,
  Cold,
  Warm,
  Dry,
  Wet,
  Humid,
  Dusty,
  Muddy,
  Sandy,
  Rocky,
  Icy,
  Snowy,
  Rainy,
  Stormy,
  Windy as WindyIcon,
  Foggy,
  Sunny as SunnyIcon,
  Cloudy as CloudyIcon2,
  Overcast,
  Clear,
  Night as NightIcon,
  Dawn,
  Dusk,
  Twilight,
  Morning,
  Afternoon,
  Evening,
  Midnight,
  Noon,
} from "lucide-react";

export interface NavItem {
  name: string;
  href: string;
  icon: React.ElementType;
  roles: string[];
  section?: string;
  badge?: string;
  badgeColor?: string;
}

export interface SubNavItem {
  name: string;
  href: string;
  icon: React.ElementType;
  parent: string;
  roles: string[];
  badge?: string;
  badgeColor?: string;
}

// Main Menu Items
export const menuItems: NavItem[] = [
  // ==================== MAIN SECTION ====================
  {
    name: "Dashboard",
    href: "/dashboard",
    icon: LayoutDashboard,
    roles: ["all"],
    section: "main",
  },
  {
    name: "My Tasks",
    href: "/tasks",
    icon: CheckSquare,
    roles: ["all"],
    section: "main",
    badge: "12",
    badgeColor: "bg-indigo-500",
  },
  {
    name: "My Profile",
    href: "/profile",
    icon: Settings,
    roles: ["all"],
    section: "main",
  },
  {
    name: "My Attendance",
    href: "/my-attendance",
    icon: Clock,
    roles: ["employee", "line_manager"],
    section: "main",
  },
  {
    name: "My Leaves",
    href: "/my-leaves",
    icon: FileText,
    roles: ["employee", "line_manager"],
    section: "main",
  },
  {
    name: "My Performance",
    href: "/my-performance",
    icon: Award,
    roles: ["employee"],
    section: "main",
  },
  {
    name: "My Team",
    href: "/my-team",
    icon: Users,
    roles: ["line_manager", "dept_manager"],
    section: "main",
    badge: "5",
    badgeColor: "bg-emerald-500",
  },

  // ==================== ADMIN SECTION ====================
  {
    name: "User Management",
    href: "/users",
    icon: Users,
    roles: ["super_admin", "admin", "hr_manager"],
    section: "admin",
  },
  {
    name: "Role Management",
    href: "/roles",
    icon: UserCog,
    roles: ["super_admin", "admin"],
    section: "admin",
  },
  {
    name: "Department Management",
    href: "/departments",
    icon: Building2,
    roles: ["super_admin", "admin", "dept_manager"],
    section: "admin",
  },
  {
    name: "Task Board",
    href: "/tasks/all",
    icon: FolderKanban,
    roles: ["super_admin", "admin", "dept_manager", "project_manager"],
    section: "admin",
  },
  {
    name: "Project Overview",
    href: "/projects",
    icon: Briefcase,
    roles: ["super_admin", "admin", "dept_manager", "project_manager"],
    section: "admin",
  },
  {
    name: "Workflow Builder",
    href: "/workflows",
    icon: GitBranch,
    roles: ["super_admin", "admin"],
    section: "admin",
  },

  // ==================== HR SECTION ====================
  {
    name: "Employee Directory",
    href: "/employees",
    icon: Users,
    roles: ["super_admin", "admin", "hr_manager"],
    section: "hr",
  },
  {
    name: "Attendance Records",
    href: "/attendance",
    icon: Calendar,
    roles: ["super_admin", "admin", "hr_manager", "dept_manager"],
    section: "hr",
  },
  {
    name: "Leave Requests",
    href: "/leaves",
    icon: FileCheck,
    roles: ["super_admin", "admin", "hr_manager", "dept_manager"],
    section: "hr",
    badge: "8",
    badgeColor: "bg-amber-500",
  },
  {
    name: "Recruitment",
    href: "/recruitment",
    icon: UserPlus,
    roles: ["super_admin", "admin", "hr_manager"],
    section: "hr",
    badge: "3",
    badgeColor: "bg-green-500",
  },
  {
    name: "Onboarding",
    href: "/onboarding",
    icon: UserCheck,
    roles: ["super_admin", "admin", "hr_manager"],
    section: "hr",
  },
  {
    name: "Offboarding",
    href: "/offboarding",
    icon: UserMinus,
    roles: ["super_admin", "admin", "hr_manager"],
    section: "hr",
  },
  {
    name: "Training",
    href: "/training",
    icon: BookOpen,
    roles: ["super_admin", "admin", "hr_manager"],
    section: "hr",
  },
  {
    name: "Payroll",
    href: "/payroll",
    icon: DollarSign,
    roles: ["super_admin", "admin", "hr_manager"],
    section: "hr",
  },

  // ==================== REPORTS SECTION ====================
  {
    name: "Reports",
    href: "/reports",
    icon: BarChart3,
    roles: ["super_admin", "admin", "dept_manager", "hr_manager"],
    section: "reports",
  },
  {
    name: "Analytics Dashboard",
    href: "/analytics",
    icon: TrendingUp,
    roles: ["super_admin", "admin", "dept_manager"],
    section: "reports",
  },
  {
    name: "KPI Tracker",
    href: "/kpi",
    icon: Target,
    roles: ["super_admin", "admin", "hr_manager", "dept_manager"],
    section: "reports",
  },
  {
    name: "Export Center",
    href: "/exports",
    icon: Download,
    roles: ["super_admin", "admin", "dept_manager", "hr_manager"],
    section: "reports",
  },

  // ==================== COMMUNICATION SECTION ====================
  {
    name: "Announcements",
    href: "/announcements",
    icon: Bell,
    roles: ["all"],
    section: "communication",
  },
  {
    name: "Messages",
    href: "/messages",
    icon: MessageSquare,
    roles: ["all"],
    section: "communication",
    badge: "5",
    badgeColor: "bg-blue-500",
  },
  {
    name: "Notifications",
    href: "/notifications",
    icon: Mail,
    roles: ["all"],
    section: "communication",
    badge: "12",
    badgeColor: "bg-red-500",
  },
  {
    name: "Team Chat",
    href: "/chat",
    icon: MessageSquare,
    roles: ["all"],
    section: "communication",
  },

  // ==================== WORKFLOW SECTION ====================
  {
    name: "Approval Requests",
    href: "/approvals",
    icon: FileCheck,
    roles: ["super_admin", "admin", "dept_manager"],
    section: "workflow",
    badge: "2",
    badgeColor: "bg-purple-500",
  },
  {
    name: "Audit Logs",
    href: "/audit-logs",
    icon: Activity,
    roles: ["super_admin", "admin"],
    section: "workflow",
  },

  // ==================== SYSTEM SECTION ====================
  {
    name: "Settings",
    href: "/settings",
    icon: Settings,
    roles: ["super_admin", "admin", "employee"],
    section: "system",
  },
  {
    name: "Security",
    href: "/security",
    icon: Shield,
    roles: ["super_admin", "admin"],
    section: "system",
  },
  {
    name: "Integrations",
    href: "/integrations",
    icon: Zap,
    roles: ["super_admin"],
    section: "system",
  },
  {
    name: "Billing",
    href: "/billing",
    icon: CreditCard,
    roles: ["super_admin", "admin"],
    section: "system",
  },
  {
    name: "API Keys",
    href: "/api-keys",
    icon: Key,
    roles: ["super_admin", "admin"],
    section: "system",
  },
  {
    name: "Webhooks",
    href: "/webhooks",
    icon: GitBranch,
    roles: ["super_admin"],
    section: "system",
  },
  {
    name: "Backup",
    href: "/backup",
    icon: Database,
    roles: ["super_admin"],
    section: "system",
  },

  // ==================== SUPPORT SECTION ====================
  {
    name: "Help Center",
    href: "/help",
    icon: HelpCircle,
    roles: ["all"],
    section: "support",
  },
  {
    name: "Support Ticket",
    href: "/support",
    icon: LifeBuoy,
    roles: ["all"],
    section: "support",
  },
  {
    name: "Documentation",
    href: "/docs",
    icon: BookOpen,
    roles: ["all"],
    section: "support",
  },
  {
    name: "API Documentation",
    href: "/api-docs",
    icon: FileText,
    roles: ["all"],
    section: "support",
  },
  {
    name: "System Status",
    href: "/status",
    icon: Activity,
    roles: ["all"],
    section: "support",
  },
  {
    name: "Feedback",
    href: "/feedback",
    icon: MessageSquare,
    roles: ["all"],
    section: "support",
  },
  {
    name: "Roadmap",
    href: "/roadmap",
    icon: Rocket,
    roles: ["all"],
    section: "support",
  },
  {
    name: "Changelog",
    href: "/changelog",
    icon: GitBranch,
    roles: ["all"],
    section: "support",
  },
];

// Submenu Items
export const subMenuItems: SubNavItem[] = [
  // User Management Submenus
  {
    name: "All Users",
    href: "/users/all",
    icon: Users,
    parent: "User Management",
    roles: ["super_admin", "admin", "hr_manager"],
  },
  {
    name: "Pending Approvals",
    href: "/users/pending",
    icon: UserPlus,
    parent: "User Management",
    roles: ["super_admin", "admin", "hr_manager"],
    badge: "3",
    badgeColor: "bg-amber-500",
  },
  {
    name: "Roles & Permissions",
    href: "/users/roles",
    icon: UserCog,
    parent: "User Management",
    roles: ["super_admin", "admin"],
  },
  {
    name: "Inactive Users",
    href: "/users/inactive",
    icon: UserX,
    parent: "User Management",
    roles: ["super_admin", "admin", "hr_manager"],
  },
  {
    name: "Bulk Import",
    href: "/users/import",
    icon: Download,
    parent: "User Management",
    roles: ["super_admin", "admin", "hr_manager"],
  },
  {
    name: "Bulk Export",
    href: "/users/export",
    icon: Download,
    parent: "User Management",
    roles: ["super_admin", "admin", "hr_manager"],
  },

  // Reports Submenus
  {
    name: "Task Reports",
    href: "/reports/tasks",
    icon: CheckSquare,
    parent: "Reports",
    roles: ["super_admin", "admin", "dept_manager"],
  },
  {
    name: "User Reports",
    href: "/reports/users",
    icon: Users,
    parent: "Reports",
    roles: ["super_admin", "admin", "hr_manager"],
  },
  {
    name: "Attendance Reports",
    href: "/reports/attendance",
    icon: Calendar,
    parent: "Reports",
    roles: ["super_admin", "admin", "hr_manager", "dept_manager"],
  },
  {
    name: "Performance Reports",
    href: "/reports/performance",
    icon: Award,
    parent: "Reports",
    roles: ["super_admin", "admin", "dept_manager", "hr_manager"],
  },
  {
    name: "Leave Reports",
    href: "/reports/leaves",
    icon: FileText,
    parent: "Reports",
    roles: ["super_admin", "admin", "hr_manager"],
  },
  {
    name: "Financial Reports",
    href: "/reports/financial",
    icon: DollarSign,
    parent: "Reports",
    roles: ["super_admin", "admin"],
  },
  {
    name: "Custom Reports",
    href: "/reports/custom",
    icon: PieChart,
    parent: "Reports",
    roles: ["super_admin", "admin"],
  },
  {
    name: "Scheduled Reports",
    href: "/reports/scheduled",
    icon: Calendar,
    parent: "Reports",
    roles: ["super_admin", "admin"],
  },

  // Settings Submenus
  {
    name: "General Settings",
    href: "/settings/general",
    icon: Settings,
    parent: "Settings",
    roles: ["super_admin", "admin"],
  },
  {
    name: "Profile Settings",
    href: "/settings/profile",
    icon: UserIcon,
    parent: "Settings",
    roles: ["all"],
  },
  {
    name: "Security Settings",
    href: "/settings/security",
    icon: Shield,
    parent: "Settings",
    roles: ["super_admin", "admin"],
  },
  {
    name: "Notification Settings",
    href: "/settings/notifications",
    icon: Bell,
    parent: "Settings",
    roles: ["all"],
  },
  {
    name: "Email Settings",
    href: "/settings/email",
    icon: Mail,
    parent: "Settings",
    roles: ["super_admin", "admin"],
  },
  {
    name: "Theme Settings",
    href: "/settings/theme",
    icon: LayoutDashboard,
    parent: "Settings",
    roles: ["all"],
  },
  {
    name: "Language Settings",
    href: "/settings/language",
    icon: Globe,
    parent: "Settings",
    roles: ["all"],
  },
  {
    name: "Timezone Settings",
    href: "/settings/timezone",
    icon: Clock,
    parent: "Settings",
    roles: ["all"],
  },
];

// Section titles for sidebar grouping
export const sectionTitles: Record<string, string> = {
  main: "MAIN",
  admin: "ADMINISTRATION",
  hr: "HUMAN RESOURCES",
  reports: "REPORTS & ANALYTICS",
  communication: "COMMUNICATION",
  workflow: "WORKFLOW",
  system: "SYSTEM",
  support: "SUPPORT & RESOURCES",
};

// Section icons for sidebar
export const sectionIcons: Record<string, React.ElementType> = {
  main: LayoutDashboard,
  admin: Shield,
  hr: Users,
  reports: BarChart3,
  communication: MessageSquare,
  workflow: GitBranch,
  system: Settings,
  support: HelpCircle,
};
