// lucide-react icons (only verified, commonly available icons)
import {
  LayoutDashboard,
  CheckSquare,
  Settings,
  Clock,
  FileText,
  Users,
  UserCog,
  Building2,
  FolderKanban,
  Briefcase,
  Calendar,
  FileCheck,
  UserPlus,
  TrendingUp,
  Award,
  PieChart,
  Target,
  Download,
  Bell,
  MessageSquare,
  Mail,
  GitBranch,
  Activity,
  Zap,
  Shield,
  BarChart3,
  CreditCard,
  HelpCircle,
  LifeBuoy,
  BookOpen,
  UserCheck,
  UserX,
  UserMinus,
  DollarSign,
  Key,
  Database,
  Globe,
  Rocket,
  Star,
  Eye,
  Edit2,
  Trash2,
  Plus,
  Search,
  Filter,
  RefreshCw,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronDown,
  Menu,
  X,
  Home,
  LogOut,
  User,
  Lock,
  Unlock,
  CheckCircle,
  AlertCircle,
  Info,
  Loader2,
  ArrowRight,
  ArrowLeft,
  CalendarDays,
  Timer,
  AlertTriangle,
  Megaphone,
  Send,
  Inbox,
  Archive,
  Copy,
  Link2,
  ExternalLink,
  Folder,
  FolderOpen,
  FolderPlus,
  File,
  FileSpreadsheet,
  Image,
  Video,
  Music,
  Code,
  Terminal,
  Monitor,
  Smartphone,
  Tablet,
  Laptop,
  Camera,
  Mic,
  Headphones,
  Printer,
  Wifi,
  Bluetooth,
  Server,
  Cloud,
  Network,
  Map,
  MapPin,
  Compass,
  Navigation,
  Building,
  Hospital,
  School,
  Library,
  Coffee,
  Heart,
  Crown,
  Trophy,
  Medal,
  Gem,
  Diamond,
  Sparkles,
  Flag,
  LineChart,
  BarChart,
  Sun,
  Moon,
  CloudRain,
  Wind,
  Waves,
  Thermometer,
  Snowflake,
  Flame,
  Car,
  Bus,
  Train,
  Plane,
  Ship,
} from "lucide-react";

export interface NavItem {
  name: string;
  href: string;
  icon: React.ElementType;
  roles: string[];
  section?: string;
  badge?: string;
  badgeColor?: string;
}

export interface SubNavItem {
  name: string;
  href: string;
  icon: React.ElementType;
  parent: string;
  roles: string[];
  badge?: string;
  badgeColor?: string;
}

// Main Menu Items
export const menuItems: NavItem[] = [
  // ==================== MAIN SECTION ====================
  {
    name: "Dashboard",
    href: "/dashboard",
    icon: LayoutDashboard,
    roles: ["all"],
    section: "main",
  },
  {
    name: "My Tasks",
    href: "/tasks",
    icon: CheckSquare,
    roles: ["all"],
    section: "main",
    badge: "12",
    badgeColor: "bg-indigo-500",
  },
  {
    name: "My Profile",
    href: "/profile",
    icon: User,
    roles: ["all"],
    section: "main",
  },
  {
    name: "My Attendance",
    href: "/my-attendance",
    icon: Clock,
    roles: ["employee", "line_manager"],
    section: "main",
  },
  {
    name: "My Leaves",
    href: "/my-leaves",
    icon: FileText,
    roles: ["employee", "line_manager"],
    section: "main",
  },
  {
    name: "My Performance",
    href: "/my-performance",
    icon: TrendingUp,
    roles: ["employee"],
    section: "main",
  },
  {
    name: "My Team",
    href: "/my-team",
    icon: Users,
    roles: ["line_manager", "dept_manager"],
    section: "main",
    badge: "5",
    badgeColor: "bg-emerald-500",
  },

  // ==================== ADMIN SECTION ====================
  {
    name: "User Management",
    href: "/users",
    icon: Users,
    roles: ["super_admin", "admin", "hr_manager"],
    section: "admin",
  },
  {
    name: "Role Management",
    href: "/roles",
    icon: UserCog,
    roles: ["super_admin", "admin"],
    section: "admin",
  },
  {
    name: "Department Management",
    href: "/departments",
    icon: Building2,
    roles: ["super_admin", "admin", "dept_manager"],
    section: "admin",
  },
  {
    name: "Task Board",
    href: "/tasks/all",
    icon: FolderKanban,
    roles: ["super_admin", "admin", "dept_manager", "project_manager"],
    section: "admin",
  },
  {
    name: "Project Overview",
    href: "/projects",
    icon: Briefcase,
    roles: ["super_admin", "admin", "dept_manager", "project_manager"],
    section: "admin",
  },
  {
    name: "Workflow Builder",
    href: "/workflows",
    icon: GitBranch,
    roles: ["super_admin", "admin"],
    section: "admin",
  },

  // ==================== HR SECTION ====================
  {
    name: "Employee Directory",
    href: "/employees",
    icon: Users,
    roles: ["super_admin", "admin", "hr_manager"],
    section: "hr",
  },
  {
    name: "Attendance Records",
    href: "/attendance",
    icon: Calendar,
    roles: ["super_admin", "admin", "hr_manager", "dept_manager"],
    section: "hr",
  },
  {
    name: "Leave Requests",
    href: "/leaves",
    icon: FileCheck,
    roles: ["super_admin", "admin", "hr_manager", "dept_manager"],
    section: "hr",
    badge: "8",
    badgeColor: "bg-amber-500",
  },
  {
    name: "Recruitment",
    href: "/recruitment",
    icon: UserPlus,
    roles: ["super_admin", "admin", "hr_manager"],
    section: "hr",
    badge: "3",
    badgeColor: "bg-green-500",
  },
  {
    name: "Onboarding",
    href: "/onboarding",
    icon: UserCheck,
    roles: ["super_admin", "admin", "hr_manager"],
    section: "hr",
  },
  {
    name: "Offboarding",
    href: "/offboarding",
    icon: UserMinus,
    roles: ["super_admin", "admin", "hr_manager"],
    section: "hr",
  },
  {
    name: "Training",
    href: "/training",
    icon: BookOpen,
    roles: ["super_admin", "admin", "hr_manager"],
    section: "hr",
  },
  {
    name: "Payroll",
    href: "/payroll",
    icon: DollarSign,
    roles: ["super_admin", "admin", "hr_manager"],
    section: "hr",
  },

  // ==================== REPORTS SECTION ====================
  {
    name: "Reports",
    href: "/reports",
    icon: BarChart3,
    roles: ["super_admin", "admin", "dept_manager", "hr_manager"],
    section: "reports",
  },
  {
    name: "Analytics Dashboard",
    href: "/analytics",
    icon: TrendingUp,
    roles: ["super_admin", "admin", "dept_manager"],
    section: "reports",
  },
  {
    name: "KPI Tracker",
    href: "/kpi",
    icon: Target,
    roles: ["super_admin", "admin", "hr_manager", "dept_manager"],
    section: "reports",
  },
  {
    name: "Export Center",
    href: "/exports",
    icon: Download,
    roles: ["super_admin", "admin", "dept_manager", "hr_manager"],
    section: "reports",
  },

  // ==================== COMMUNICATION SECTION ====================
  {
    name: "Announcements",
    href: "/announcements",
    icon: Bell,
    roles: ["all"],
    section: "communication",
  },
  {
    name: "Messages",
    href: "/messages",
    icon: MessageSquare,
    roles: ["all"],
    section: "communication",
    badge: "5",
    badgeColor: "bg-blue-500",
  },
  {
    name: "Notifications",
    href: "/notifications",
    icon: Mail,
    roles: ["all"],
    section: "communication",
    badge: "12",
    badgeColor: "bg-red-500",
  },
  {
    name: "Team Chat",
    href: "/chat",
    icon: MessageSquare,
    roles: ["all"],
    section: "communication",
  },

  // ==================== WORKFLOW SECTION ====================
  {
    name: "Approval Requests",
    href: "/approvals",
    icon: FileCheck,
    roles: ["super_admin", "admin", "dept_manager"],
    section: "workflow",
    badge: "2",
    badgeColor: "bg-purple-500",
  },
  {
    name: "Audit Logs",
    href: "/audit-logs",
    icon: Activity,
    roles: ["super_admin", "admin"],
    section: "workflow",
  },

  // ==================== SYSTEM SECTION ====================
  {
    name: "Settings",
    href: "/settings",
    icon: Settings,
    roles: ["super_admin", "admin", "employee"],
    section: "system",
  },
  {
    name: "Security",
    href: "/security",
    icon: Shield,
    roles: ["super_admin", "admin"],
    section: "system",
  },
  {
    name: "Integrations",
    href: "/integrations",
    icon: Zap,
    roles: ["super_admin"],
    section: "system",
  },
  {
    name: "Billing",
    href: "/billing",
    icon: CreditCard,
    roles: ["super_admin", "admin"],
    section: "system",
  },
  {
    name: "API Keys",
    href: "/api-keys",
    icon: Key,
    roles: ["super_admin", "admin"],
    section: "system",
  },
  {
    name: "Webhooks",
    href: "/webhooks",
    icon: GitBranch,
    roles: ["super_admin"],
    section: "system",
  },
  {
    name: "Backup",
    href: "/backup",
    icon: Database,
    roles: ["super_admin"],
    section: "system",
  },

  // ==================== SUPPORT SECTION ====================
  {
    name: "Help Center",
    href: "/help",
    icon: HelpCircle,
    roles: ["all"],
    section: "support",
  },
  {
    name: "Support Ticket",
    href: "/support",
    icon: LifeBuoy,
    roles: ["all"],
    section: "support",
  },
  {
    name: "Documentation",
    href: "/docs",
    icon: BookOpen,
    roles: ["all"],
    section: "support",
  },
  {
    name: "API Documentation",
    href: "/api-docs",
    icon: FileText,
    roles: ["all"],
    section: "support",
  },
  {
    name: "System Status",
    href: "/status",
    icon: Activity,
    roles: ["all"],
    section: "support",
  },
  {
    name: "Feedback",
    href: "/feedback",
    icon: MessageSquare,
    roles: ["all"],
    section: "support",
  },
  {
    name: "Roadmap",
    href: "/roadmap",
    icon: Rocket,
    roles: ["all"],
    section: "support",
  },
  {
    name: "Changelog",
    href: "/changelog",
    icon: GitBranch,
    roles: ["all"],
    section: "support",
  },
];

// Submenu Items
export const subMenuItems: SubNavItem[] = [
  // User Management Submenus
  {
    name: "All Users",
    href: "/users/all",
    icon: Users,
    parent: "User Management",
    roles: ["super_admin", "admin", "hr_manager"],
  },
  {
    name: "Pending Approvals",
    href: "/users/pending",
    icon: UserPlus,
    parent: "User Management",
    roles: ["super_admin", "admin", "hr_manager"],
    badge: "3",
    badgeColor: "bg-amber-500",
  },
  {
    name: "Roles & Permissions",
    href: "/users/roles",
    icon: UserCog,
    parent: "User Management",
    roles: ["super_admin", "admin"],
  },
  {
    name: "Inactive Users",
    href: "/users/inactive",
    icon: UserX,
    parent: "User Management",
    roles: ["super_admin", "admin", "hr_manager"],
  },
  {
    name: "Bulk Import",
    href: "/users/import",
    icon: FileSpreadsheet,
    parent: "User Management",
    roles: ["super_admin", "admin", "hr_manager"],
  },
  {
    name: "Bulk Export",
    href: "/users/export",
    icon: Download,
    parent: "User Management",
    roles: ["super_admin", "admin", "hr_manager"],
  },

  // Reports Submenus
  {
    name: "Task Reports",
    href: "/reports/tasks",
    icon: CheckSquare,
    parent: "Reports",
    roles: ["super_admin", "admin", "dept_manager"],
  },
  {
    name: "User Reports",
    href: "/reports/users",
    icon: Users,
    parent: "Reports",
    roles: ["super_admin", "admin", "hr_manager"],
  },
  {
    name: "Attendance Reports",
    href: "/reports/attendance",
    icon: Calendar,
    parent: "Reports",
    roles: ["super_admin", "admin", "hr_manager", "dept_manager"],
  },
  {
    name: "Performance Reports",
    href: "/reports/performance",
    icon: Award,
    parent: "Reports",
    roles: ["super_admin", "admin", "dept_manager", "hr_manager"],
  },
  {
    name: "Leave Reports",
    href: "/reports/leaves",
    icon: FileText,
    parent: "Reports",
    roles: ["super_admin", "admin", "hr_manager"],
  },
  {
    name: "Financial Reports",
    href: "/reports/financial",
    icon: DollarSign,
    parent: "Reports",
    roles: ["super_admin", "admin"],
  },
  {
    name: "Custom Reports",
    href: "/reports/custom",
    icon: PieChart,
    parent: "Reports",
    roles: ["super_admin", "admin"],
  },
  {
    name: "Scheduled Reports",
    href: "/reports/scheduled",
    icon: Calendar,
    parent: "Reports",
    roles: ["super_admin", "admin"],
  },

  // Settings Submenus
  {
    name: "General Settings",
    href: "/settings/general",
    icon: Settings,
    parent: "Settings",
    roles: ["super_admin", "admin"],
  },
  {
    name: "Profile Settings",
    href: "/settings/profile",
    icon: User,
    parent: "Settings",
    roles: ["all"],
  },
  {
    name: "Security Settings",
    href: "/settings/security",
    icon: Shield,
    parent: "Settings",
    roles: ["super_admin", "admin"],
  },
  {
    name: "Notification Settings",
    href: "/settings/notifications",
    icon: Bell,
    parent: "Settings",
    roles: ["all"],
  },
  {
    name: "Email Settings",
    href: "/settings/email",
    icon: Mail,
    parent: "Settings",
    roles: ["super_admin", "admin"],
  },
  {
    name: "Theme Settings",
    href: "/settings/theme",
    icon: LayoutDashboard,
    parent: "Settings",
    roles: ["all"],
  },
  {
    name: "Language Settings",
    href: "/settings/language",
    icon: Globe,
    parent: "Settings",
    roles: ["all"],
  },
  {
    name: "Timezone Settings",
    href: "/settings/timezone",
    icon: Clock,
    parent: "Settings",
    roles: ["all"],
  },
];

// Section titles for sidebar grouping
export const sectionTitles: Record<string, string> = {
  main: "MAIN",
  admin: "ADMINISTRATION",
  hr: "HUMAN RESOURCES",
  reports: "REPORTS & ANALYTICS",
  communication: "COMMUNICATION",
  workflow: "WORKFLOW",
  system: "SYSTEM",
  support: "SUPPORT & RESOURCES",
};

// Section icons for sidebar
export const sectionIcons: Record<string, React.ElementType> = {
  main: LayoutDashboard,
  admin: Shield,
  hr: Users,
  reports: BarChart3,
  communication: MessageSquare,
  workflow: GitBranch,
  system: Settings,
  support: HelpCircle,
};
