// lib/menuItems.ts
import {
  LayoutDashboard,
  CheckSquare,
  Settings,
  Clock,
  FileText,
  Users,
  UserCog,
  Building2,
  FolderKanban,
  Briefcase,
  Calendar,
  FileCheck,
  UserPlus,
  TrendingUp,
  Award,
  PieChart,
  Target,
  Download,
  Bell,
  MessageSquare,
  Mail,
  GitBranch,
  Activity,
  Zap,
  Shield,
  BarChart3,
  CreditCard,
  HelpCircle,
  LifeBuoy,
  BookOpen,
  Grid3X3,
  ListChecks,
  ClipboardList,
  UserCheck,
  UserX,
  UserMinus,
  UserSearch,
  CalendarDays,
  Clock8,
  Timer,
  AlarmClock,
  CheckCheck,
  XCircle,
  AlertTriangle,
  Info,
  Megaphone,
  Send,
  Inbox,
  Archive,
  Trash2,
  Edit,
  PlusCircle,
  MinusCircle,
  RefreshCw,
  Lock,
  Key,
  Fingerprint,
  Eye,
  EyeOff,
  Globe,
  Server,
  Database,
  Cloud,
  Wifi,
  Battery,
  Cpu,
  HardDrive,
  Monitor,
  Printer,
  Scan,
  QrCode,
  CreditCard as CreditCardIcon,
  Wallet,
  DollarSign,
  Percent,
  Calculator,
  Receipt,
  FileSpreadsheet,
  FileText as FileTextIcon,
  FileImage,
  FileVideo,
  FileAudio,
  FileArchive,
  FileCode,
  FileJson,
  FilePdf,
  FileWord,
  FileExcel,
  FilePowerpoint,
  Folder,
  FolderOpen,
  FolderPlus,
  FolderSearch,
  FolderSync,
  Share2,
  Link2,
  Copy,
  Cut,
  Paste,
  Undo,
  Redo,
  Bold,
  Italic,
  Underline,
  AlignLeft,
  AlignCenter,
  AlignRight,
  AlignJustify,
  List,
  ListOrdered,
  ListChecks as ListChecksIcon,
  CheckSquare as CheckSquareIcon,
  Square,
  Circle,
  Triangle,
  Hexagon,
  Pentagon,
  Octagon,
  Star,
  Heart,
  ThumbsUp,
  ThumbsDown,
  Smile,
  Frown,
  Meh,
  Laugh,
  Cry,
  Angry,
  WifiOff,
  Signal,
  SignalLow,
  SignalMedium,
  SignalHigh,
  Bluetooth,
  BluetoothConnected,
  BluetoothOff,
  Usb,
  Plug,
  PlugZap,
  Power,
  PowerOff,
  BatteryFull,
  BatteryLow,
  BatteryMedium,
  BatteryCharging,
  BatteryWarning,
  Speaker,
  SpeakerOff,
  SpeakerLow,
  SpeakerMedium,
  SpeakerHigh,
  Mic,
  MicOff,
  Mic2,
  Headphones,
  HeadphoneOff,
  Music,
  Music2,
  Music3,
  Music4,
  Radio,
  RadioTower,
  Tv,
  Tv2,
  MonitorPlay,
  MonitorPause,
  MonitorStop,
  MonitorX,
  Smartphone,
  Tablet,
  Laptop,
  Computer,
  Watch,
  WatchIcon,
  Camera,
  CameraOff,
  Video,
  VideoOff,
  Film,
  Clapperboard,
  Theater,
  Sparkles,
  Gem,
  Diamond,
  Medal,
  Trophy,
  Award as AwardIcon,
  Crown,
  Star as StarIcon,
  Rocket,
  Space,
  Orbit,
  Satellite,
  Planet,
  Globe2,
  Map,
  MapPin,
  Compass,
  Navigation,
  Navigation2,
  NavigationOff,
  Home,
  Warehouse,
  Factory,
  Store,
  Building,
  Building2 as BuildingIcon,
  Church,
  Hospital,
  School,
  University,
  Library,
  Coffee,
  Beer,
  Wine,
  Cake,
  Pizza,
  Burger,
  Apple,
  Leaf,
  Tree,
  Flower,
  Sun,
  Moon,
  CloudRain,
  CloudSnow,
  CloudLightning,
  CloudFog,
  Wind,
  Tornado,
  Waves,
  Droplets,
  Thermometer,
  Snowflake,
  Flame,
  Fire,
  Zap as ZapIcon,
  BatteryCharging as BatteryChargingIcon,
  Car,
  Bus,
  Train,
  Plane,
  Ship,
  Bike,
  Run,
  Walk,
  Move,
  RotateCw,
  RotateCcw,
  ZoomIn,
  ZoomOut,
  Maximize,
  Minimize,
  Maximize2,
  Minimize2,
  Resize,
  Crop,
  Scissors,
  Ruler,
  Weight,
  Scale,
  Gauge,
  Speedometer,
  Tachometer,
  Activity as ActivityIcon,
  HeartPulse,
  Brain,
  Bone,
  Tooth,
  Stethoscope,
  Syringe,
  Pill,
  Hospital as HospitalIcon,
  Ambulance,
  Bandage,
  Thermometer as ThermometerIcon,
  Microscope,
  TestTube,
  TestTubes,
  Flask,
  Beaker,
  Atom,
  Dna,
  Virus,
  Bacteria,
  Bug,
  BugOff,
  Spider,
  Bee,
  Butterfly,
  Fish,
  Bird,
  Cat,
  Dog,
  Rabbit,
  Turtle,
  Fox,
  Lion,
  Tiger,
  Elephant,
  Giraffe,
  Monkey,
  Panda,
  Penguin,
  Dolphin,
  Whale,
  Shark,
  Octopus,
  Crab,
  Lobster,
  Snail,
  Frog,
  Lizard,
  Snake,
  Dragon,
  Unicorn,
  Phoenix,
  Angel,
  Devil,
  Ghost,
  Skull,
  Pumpkin,
  Hat,
  Glasses,
  Sunglasses,
  Goggles,
  Mask,
  GasMask,
  Helmet,
  ShieldCheck,
  ShieldAlert,
  ShieldX,
  ShieldPlus,
  ShieldMinus,
  ShieldOff,
  LockKeyhole,
  LockOpen,
  Unlock,
  KeyRound,
  KeySquare,
  Badge,
  BadgeCheck,
  BadgeAlert,
  BadgeX,
  BadgePlus,
  BadgeMinus,
  BadgeOff,
  Verified,
  CheckVerified,
  AlertOctagon,
  AlertCircle as AlertCircleIcon,
  AlertTriangle as AlertTriangleIcon,
  Info as InfoIcon,
  HelpCircle as HelpCircleIcon,
  XCircle as XCircleIcon,
  CheckCircle,
  PlusCircle as PlusCircleIcon,
  MinusCircle as MinusCircleIcon,
  DivideCircle,
  EqualCircle,
  PercentCircle,
  Hash,
  Asterisk,
  AtSign,
  DollarSign as DollarSignIcon,
  Euro,
  Pound,
  Yen,
  Ruble,
  Rupee,
  Won,
  Bitcoin,
  Ethereum,
  Ltc,
  Doge,
  Cardano,
  Polkadot,
  Solana,
  Chainlink,
  Polygon,
  Aave,
  Uniswap,
  Compound,
  Maker,
  Curve,
  Sushi,
  Pancake,
  Cake as CakeIcon,
  Egg,
  EggFried,
  Croissant,
  Bread,
  Cheese,
  Milk,
  Coffee as CoffeeIcon,
  Tea,
  Soda,
  Beer as BeerIcon,
  Wine as WineIcon,
  Cocktail,
  Champagne,
  Whiskey,
  Vodka,
  Gin,
  Rum,
  Tequila,
  Brandy,
  Liqueur,
  Vermouth,
  Sherry,
  Port,
  Sake,
  Cider,
  Kombucha,
  Juice,
  Water,
  SparklingWater,
  EnergyDrink,
  SportsDrink,
  ProteinShake,
  Smoothie,
  Milkshake,
  IceCream,
  IceCream2,
  Cookie,
  Donut,
  Muffin,
  Cupcake,
  Pie,
  Brownie,
  Blush,
  Flushed,
  Grin,
  Happy,
  Sad,
  Sleepy,
  Tired,
  Cool,
  Hot,
  Cold,
  Warm,
  Dry,
  Wet,
  Humid,
  Dusty,
  Muddy,
  Sandy,
  Rocky,
  Icy,
  Snowy,
  Rainy,
  Stormy,
  Windy,
  Foggy,
  Sunny,
  Cloudy,
  PartlyCloudy,
  Overcast,
  Clear,
  Night,
  Dawn,
  Dusk,
  Twilight,
  Morning,
  Afternoon,
  Evening,
  Midnight,
  Noon,
  Midnight as MidnightIcon,
  Noon as NoonIcon,
  Sunrise,
  Sunset,
  Moonrise,
  Moonset,
  Starry,
  ShootingStar,
  Comet,
  Asteroid,
  Meteor,
  BlackHole,
  Nebula,
  Galaxy,
  Universe,
  Cosmos,
  SpaceShip,
  Ufo,
  Alien,
  Robot,
  Android,
  Apple as AppleIcon,
  Windows,
  Linux,
  Ubuntu,
  Debian,
  Fedora,
  CentOS,
  RedHat,
  Arch,
  Manjaro,
  Mint,
  PopOs,
  Zorin,
  Elementary,
  Deepin,
  Kde,
  Gnome,
  Xfce,
  Lxde,
  Mate,
  Cinnamon,
  Budgie,
  Pantheon,
  Unity,
  Enlightenment,
  Awesome,
  I3,
  Hyprland,
  Sway,
  River,
  Dwl,
  Labwc,
  Wayfire,
  Weston,
  Mutter,
  Kwin,
  Compiz,
  Bspwm,
  Herbstluftwm,
  Qtile,
  Xmonad,
  Dwm,
  Spectrwm,
  Cwm,
  Fvwm,
  Afterstep,
  WindowMaker,
  Fluxbox,
  Openbox,
  Icewm,
  Jwm,
  Hacked,
  Stumpwm,
  Ratpoison,
  Evilwm,
  Aewm,
  Wmii,
  Larswm,
  Echinus,
  Frankenwm,
  Partiwm,
  Scrotwm,
  Musca,
  Wmx,
  Wm2,
  Wm3,
  Wm4,
  Wm5,
  Wm6,
  Wm7,
  Wm8,
  Wm9,
  User,
  Package,
} from "lucide-react";

export interface NavItem {
  name: string;
  href: string;
  icon: React.ElementType;
  roles: string[];
  section?: string;
  badge?: string;
  badgeColor?: string;
}

export interface SubNavItem {
  name: string;
  href: string;
  icon: React.ElementType;
  parent: string;
  roles: string[];
  badge?: string;
  badgeColor?: string;
}

// Main Menu Items
export const menuItems: NavItem[] = [
  // ==================== MAIN SECTION ====================
  {
    name: "Dashboard",
    href: "/dashboard",
    icon: LayoutDashboard,
    roles: ["all"],
    section: "main",
  },
  {
    name: "My Tasks",
    href: "/tasks",
    icon: CheckSquare,
    roles: ["all"],
    section: "main",
    badge: "12",
    badgeColor: "bg-indigo-500",
  },
  {
    name: "My Profile",
    href: "/profile",
    icon: Settings,
    roles: ["all"],
    section: "main",
  },
  {
    name: "My Attendance",
    href: "/my-attendance",
    icon: Clock,
    roles: ["employee", "line_manager"],
    section: "main",
  },
  {
    name: "My Leaves",
    href: "/my-leaves",
    icon: FileText,
    roles: ["employee", "line_manager"],
    section: "main",
  },
  {
    name: "My Performance",
    href: "/my-performance",
    icon: Award,
    roles: ["employee"],
    section: "main",
  },
  {
    name: "My Team",
    href: "/my-team",
    icon: Users,
    roles: ["line_manager", "dept_manager"],
    section: "main",
    badge: "5",
    badgeColor: "bg-emerald-500",
  },

  // ==================== ADMIN SECTION ====================
  {
    name: "User Management",
    href: "/users",
    icon: Users,
    roles: ["super_admin", "admin", "hr_manager"],
    section: "admin",
  },
  {
    name: "Role Management",
    href: "/roles",
    icon: UserCog,
    roles: ["super_admin", "admin"],
    section: "admin",
  },
  {
    name: "Department Management",
    href: "/departments",
    icon: Building2,
    roles: ["super_admin", "admin", "dept_manager"],
    section: "admin",
  },
  {
    name: "Task Board",
    href: "/tasks/all",
    icon: FolderKanban,
    roles: ["super_admin", "admin", "dept_manager", "project_manager"],
    section: "admin",
  },
  {
    name: "Project Overview",
    href: "/projects",
    icon: Briefcase,
    roles: ["super_admin", "admin", "dept_manager", "project_manager"],
    section: "admin",
  },
  {
    name: "Workflow Builder",
    href: "/workflows",
    icon: GitBranch,
    roles: ["super_admin", "admin"],
    section: "admin",
  },

  // ==================== HR SECTION ====================
  {
    name: "Employee Directory",
    href: "/employees",
    icon: Users,
    roles: ["super_admin", "admin", "hr_manager"],
    section: "hr",
  },
  {
    name: "Attendance Records",
    href: "/attendance",
    icon: Calendar,
    roles: ["super_admin", "admin", "hr_manager", "dept_manager"],
    section: "hr",
  },
  {
    name: "Leave Requests",
    href: "/leaves",
    icon: FileCheck,
    roles: ["super_admin", "admin", "hr_manager", "dept_manager"],
    section: "hr",
    badge: "8",
    badgeColor: "bg-amber-500",
  },
  {
    name: "Recruitment",
    href: "/recruitment",
    icon: UserPlus,
    roles: ["super_admin", "admin", "hr_manager"],
    section: "hr",
    badge: "3",
    badgeColor: "bg-green-500",
  },
  {
    name: "Onboarding",
    href: "/onboarding",
    icon: UserCheck,
    roles: ["super_admin", "admin", "hr_manager"],
    section: "hr",
  },
  {
    name: "Offboarding",
    href: "/offboarding",
    icon: UserMinus,
    roles: ["super_admin", "admin", "hr_manager"],
    section: "hr",
  },
  {
    name: "Training",
    href: "/training",
    icon: BookOpen,
    roles: ["super_admin", "admin", "hr_manager"],
    section: "hr",
  },
  {
    name: "Payroll",
    href: "/payroll",
    icon: DollarSign,
    roles: ["super_admin", "admin", "hr_manager"],
    section: "hr",
  },

  // ==================== REPORTS SECTION ====================
  {
    name: "Reports",
    href: "/reports",
    icon: BarChart3,
    roles: ["super_admin", "admin", "dept_manager", "hr_manager"],
    section: "reports",
  },
  {
    name: "Analytics Dashboard",
    href: "/analytics",
    icon: TrendingUp,
    roles: ["super_admin", "admin", "dept_manager"],
    section: "reports",
  },
  {
    name: "KPI Tracker",
    href: "/kpi",
    icon: Target,
    roles: ["super_admin", "admin", "hr_manager", "dept_manager"],
    section: "reports",
  },
  {
    name: "Export Center",
    href: "/exports",
    icon: Download,
    roles: ["super_admin", "admin", "dept_manager", "hr_manager"],
    section: "reports",
  },

  // ==================== COMMUNICATION SECTION ====================
  {
    name: "Announcements",
    href: "/announcements",
    icon: Bell,
    roles: ["all"],
    section: "communication",
  },
  {
    name: "Messages",
    href: "/messages",
    icon: MessageSquare,
    roles: ["all"],
    section: "communication",
    badge: "5",
    badgeColor: "bg-blue-500",
  },
  {
    name: "Notifications",
    href: "/notifications",
    icon: Mail,
    roles: ["all"],
    section: "communication",
    badge: "12",
    badgeColor: "bg-red-500",
  },
  {
    name: "Team Chat",
    href: "/chat",
    icon: MessageSquare,
    roles: ["all"],
    section: "communication",
  },

  // ==================== WORKFLOW SECTION ====================
  {
    name: "Approval Requests",
    href: "/approvals",
    icon: FileCheck,
    roles: ["super_admin", "admin", "dept_manager"],
    section: "workflow",
    badge: "2",
    badgeColor: "bg-purple-500",
  },
  {
    name: "Audit Logs",
    href: "/audit-logs",
    icon: Activity,
    roles: ["super_admin", "admin"],
    section: "workflow",
  },

  // ==================== SYSTEM SECTION ====================
  {
    name: "Settings",
    href: "/settings",
    icon: Settings,
    roles: ["super_admin", "admin", "employee"],
    section: "system",
  },
  {
    name: "Security",
    href: "/security",
    icon: Shield,
    roles: ["super_admin", "admin"],
    section: "system",
  },
  {
    name: "Integrations",
    href: "/integrations",
    icon: Zap,
    roles: ["super_admin"],
    section: "system",
  },
  {
    name: "Billing",
    href: "/billing",
    icon: CreditCard,
    roles: ["super_admin", "admin"],
    section: "system",
  },
  {
    name: "API Keys",
    href: "/api-keys",
    icon: Key,
    roles: ["super_admin", "admin"],
    section: "system",
  },
  {
    name: "Webhooks",
    href: "/webhooks",
    icon: GitBranch,
    roles: ["super_admin"],
    section: "system",
  },
  {
    name: "Backup",
    href: "/backup",
    icon: Database,
    roles: ["super_admin"],
    section: "system",
  },

  // ==================== SUPPORT SECTION ====================
  {
    name: "Help Center",
    href: "/help",
    icon: HelpCircle,
    roles: ["all"],
    section: "support",
  },
  {
    name: "Support Ticket",
    href: "/support",
    icon: LifeBuoy,
    roles: ["all"],
    section: "support",
  },
  {
    name: "Documentation",
    href: "/docs",
    icon: BookOpen,
    roles: ["all"],
    section: "support",
  },
  {
    name: "API Documentation",
    href: "/api-docs",
    icon: FileCode,
    roles: ["all"],
    section: "support",
  },
  {
    name: "System Status",
    href: "/status",
    icon: Activity,
    roles: ["all"],
    section: "support",
  },
  {
    name: "Feedback",
    href: "/feedback",
    icon: MessageSquare,
    roles: ["all"],
    section: "support",
  },
  {
    name: "Roadmap",
    href: "/roadmap",
    icon: Rocket,
    roles: ["all"],
    section: "support",
  },
  {
    name: "Changelog",
    href: "/changelog",
    icon: GitBranch,
    roles: ["all"],
    section: "support",
  },
];

// Submenu Items (for parent items that expand)
export const subMenuItems: SubNavItem[] = [
  // User Management Submenus
  {
    name: "All Users",
    href: "/users/all",
    icon: Users,
    parent: "User Management",
    roles: ["super_admin", "admin", "hr_manager"],
  },
  {
    name: "Pending Approvals",
    href: "/users/pending",
    icon: UserPlus,
    parent: "User Management",
    roles: ["super_admin", "admin", "hr_manager"],
    badge: "3",
    badgeColor: "bg-amber-500",
  },
  {
    name: "Roles & Permissions",
    href: "/users/roles",
    icon: UserCog,
    parent: "User Management",
    roles: ["super_admin", "admin"],
  },
  {
    name: "Inactive Users",
    href: "/users/inactive",
    icon: UserX,
    parent: "User Management",
    roles: ["super_admin", "admin", "hr_manager"],
  },
  {
    name: "Bulk Import",
    href: "/users/import",
    icon: FileSpreadsheet,
    parent: "User Management",
    roles: ["super_admin", "admin", "hr_manager"],
  },
  {
    name: "Bulk Export",
    href: "/users/export",
    icon: Download,
    parent: "User Management",
    roles: ["super_admin", "admin", "hr_manager"],
  },

  // Reports Submenus
  {
    name: "Task Reports",
    href: "/reports/tasks",
    icon: CheckSquare,
    parent: "Reports",
    roles: ["super_admin", "admin", "dept_manager"],
  },
  {
    name: "User Reports",
    href: "/reports/users",
    icon: Users,
    parent: "Reports",
    roles: ["super_admin", "admin", "hr_manager"],
  },
  {
    name: "Attendance Reports",
    href: "/reports/attendance",
    icon: Calendar,
    parent: "Reports",
    roles: ["super_admin", "admin", "hr_manager", "dept_manager"],
  },
  {
    name: "Performance Reports",
    href: "/reports/performance",
    icon: Award,
    parent: "Reports",
    roles: ["super_admin", "admin", "dept_manager", "hr_manager"],
  },
  {
    name: "Leave Reports",
    href: "/reports/leaves",
    icon: FileText,
    parent: "Reports",
    roles: ["super_admin", "admin", "hr_manager"],
  },
  {
    name: "Financial Reports",
    href: "/reports/financial",
    icon: DollarSign,
    parent: "Reports",
    roles: ["super_admin", "admin"],
  },
  {
    name: "Custom Reports",
    href: "/reports/custom",
    icon: PieChart,
    parent: "Reports",
    roles: ["super_admin", "admin"],
  },
  {
    name: "Scheduled Reports",
    href: "/reports/scheduled",
    icon: Calendar,
    parent: "Reports",
    roles: ["super_admin", "admin"],
  },

  // Settings Submenus
  {
    name: "General Settings",
    href: "/settings/general",
    icon: Settings,
    parent: "Settings",
    roles: ["super_admin", "admin"],
  },
  {
    name: "Profile Settings",
    href: "/settings/profile",
    icon: User,
    parent: "Settings",
    roles: ["all"],
  },
  {
    name: "Security Settings",
    href: "/settings/security",
    icon: Shield,
    parent: "Settings",
    roles: ["super_admin", "admin"],
  },
  {
    name: "Notification Settings",
    href: "/settings/notifications",
    icon: Bell,
    parent: "Settings",
    roles: ["all"],
  },
  {
    name: "Email Settings",
    href: "/settings/email",
    icon: Mail,
    parent: "Settings",
    roles: ["super_admin", "admin"],
  },
  {
    name: "Theme Settings",
    href: "/settings/theme",
    icon: LayoutDashboard,
    parent: "Settings",
    roles: ["all"],
  },
  {
    name: "Language Settings",
    href: "/settings/language",
    icon: Globe,
    parent: "Settings",
    roles: ["all"],
  },
  {
    name: "Timezone Settings",
    href: "/settings/timezone",
    icon: Clock,
    parent: "Settings",
    roles: ["all"],
  },

  // Department Management Submenus
  {
    name: "All Departments",
    href: "/departments/all",
    icon: Building2,
    parent: "Department Management",
    roles: ["super_admin", "admin", "dept_manager"],
  },
  {
    name: "Department Hierarchy",
    href: "/departments/hierarchy",
    icon: GitBranch,
    parent: "Department Management",
    roles: ["super_admin", "admin"],
  },
  {
    name: "Department Budget",
    href: "/departments/budget",
    icon: DollarSign,
    parent: "Department Management",
    roles: ["super_admin", "admin", "dept_manager"],
  },
  {
    name: "Department Assets",
    href: "/departments/assets",
    icon: FolderKanban,
    parent: "Department Management",
    roles: ["super_admin", "admin", "dept_manager"],
  },

  // Project Overview Submenus
  {
    name: "Active Projects",
    href: "/projects/active",
    icon: Briefcase,
    parent: "Project Overview",
    roles: ["super_admin", "admin", "dept_manager", "project_manager"],
  },
  {
    name: "Completed Projects",
    href: "/projects/completed",
    icon: CheckCircle,
    parent: "Project Overview",
    roles: ["super_admin", "admin", "dept_manager", "project_manager"],
  },
  {
    name: "Project Templates",
    href: "/projects/templates",
    icon: FileText,
    parent: "Project Overview",
    roles: ["super_admin", "admin"],
  },
  {
    name: "Project Resources",
    href: "/projects/resources",
    icon: Users,
    parent: "Project Overview",
    roles: ["super_admin", "admin", "dept_manager", "project_manager"],
  },

  // Recruitment Submenus
  {
    name: "Job Openings",
    href: "/recruitment/jobs",
    icon: Briefcase,
    parent: "Recruitment",
    roles: ["super_admin", "admin", "hr_manager"],
  },
  {
    name: "Applications",
    href: "/recruitment/applications",
    icon: Users,
    parent: "Recruitment",
    roles: ["super_admin", "admin", "hr_manager"],
    badge: "7",
    badgeColor: "bg-blue-500",
  },
  {
    name: "Interviews",
    href: "/recruitment/interviews",
    icon: Calendar,
    parent: "Recruitment",
    roles: ["super_admin", "admin", "hr_manager"],
    badge: "4",
    badgeColor: "bg-purple-500",
  },
  {
    name: "Candidates",
    href: "/recruitment/candidates",
    icon: UserPlus,
    parent: "Recruitment",
    roles: ["super_admin", "admin", "hr_manager"],
  },
  {
    name: "Offer Letters",
    href: "/recruitment/offers",
    icon: FileCheck,
    parent: "Recruitment",
    roles: ["super_admin", "admin", "hr_manager"],
  },

  // Analytics Submenus
  {
    name: "Business Analytics",
    href: "/analytics/business",
    icon: BarChart3,
    parent: "Analytics Dashboard",
    roles: ["super_admin", "admin"],
  },
  {
    name: "Sales Analytics",
    href: "/analytics/sales",
    icon: TrendingUp,
    parent: "Analytics Dashboard",
    roles: ["super_admin", "admin"],
  },
  {
    name: "Product Analytics",
    href: "/analytics/product",
    icon: Package,
    parent: "Analytics Dashboard",
    roles: ["super_admin", "admin"],
  },
  {
    name: "User Analytics",
    href: "/analytics/users",
    icon: Users,
    parent: "Analytics Dashboard",
    roles: ["super_admin", "admin", "hr_manager"],
  },
  {
    name: "Real-time Analytics",
    href: "/analytics/realtime",
    icon: Activity,
    parent: "Analytics Dashboard",
    roles: ["super_admin", "admin"],
  },
  {
    name: "Predictive Analytics",
    href: "/analytics/predictive",
    icon: Brain,
    parent: "Analytics Dashboard",
    roles: ["super_admin", "admin"],
  },

  // KPI Tracker Submenus
  {
    name: "Company KPIs",
    href: "/kpi/company",
    icon: Target,
    parent: "KPI Tracker",
    roles: ["super_admin", "admin"],
  },
  {
    name: "Department KPIs",
    href: "/kpi/department",
    icon: Building2,
    parent: "KPI Tracker",
    roles: ["super_admin", "admin", "dept_manager"],
  },
  {
    name: "Individual KPIs",
    href: "/kpi/individual",
    icon: User,
    parent: "KPI Tracker",
    roles: ["super_admin", "admin", "hr_manager", "dept_manager"],
  },
  {
    name: "KPI Settings",
    href: "/kpi/settings",
    icon: Settings,
    parent: "KPI Tracker",
    roles: ["super_admin", "admin"],
  },

  // Announcements Submenus
  {
    name: "Company Announcements",
    href: "/announcements/company",
    icon: Megaphone,
    parent: "Announcements",
    roles: ["all"],
  },
  {
    name: "Department Announcements",
    href: "/announcements/department",
    icon: Building2,
    parent: "Announcements",
    roles: ["all"],
  },
  {
    name: "Create Announcement",
    href: "/announcements/create",
    icon: PlusCircle,
    parent: "Announcements",
    roles: ["super_admin", "admin", "hr_manager", "dept_manager"],
  },
  {
    name: "Archive",
    href: "/announcements/archive",
    icon: Archive,
    parent: "Announcements",
    roles: ["all"],
  },

  // Messages Submenus
  {
    name: "Inbox",
    href: "/messages/inbox",
    icon: Inbox,
    parent: "Messages",
    roles: ["all"],
    badge: "8",
    badgeColor: "bg-blue-500",
  },
  {
    name: "Sent",
    href: "/messages/sent",
    icon: Send,
    parent: "Messages",
    roles: ["all"],
  },
  {
    name: "Drafts",
    href: "/messages/drafts",
    icon: FileText,
    parent: "Messages",
    roles: ["all"],
    badge: "2",
    badgeColor: "bg-gray-500",
  },
  {
    name: "Trash",
    href: "/messages/trash",
    icon: Trash2,
    parent: "Messages",
    roles: ["all"],
  },
  {
    name: "Compose",
    href: "/messages/compose",
    icon: Edit,
    parent: "Messages",
    roles: ["all"],
  },

  // Notifications Submenus
  {
    name: "All Notifications",
    href: "/notifications/all",
    icon: Bell,
    parent: "Notifications",
    roles: ["all"],
    badge: "12",
    badgeColor: "bg-red-500",
  },
  {
    name: "Unread",
    href: "/notifications/unread",
    icon: Bell,
    parent: "Notifications",
    roles: ["all"],
    badge: "8",
    badgeColor: "bg-red-500",
  },
  {
    name: "Settings",
    href: "/notifications/settings",
    icon: Settings,
    parent: "Notifications",
    roles: ["all"],
  },
];

// Section titles for sidebar grouping
export const sectionTitles: Record<string, string> = {
  main: "MAIN",
  admin: "ADMINISTRATION",
  hr: "HUMAN RESOURCES",
  reports: "REPORTS & ANALYTICS",
  communication: "COMMUNICATION",
  workflow: "WORKFLOW",
  system: "SYSTEM",
  support: "SUPPORT & RESOURCES",
};

// Section icons for sidebar
export const sectionIcons: Record<string, React.ElementType> = {
  main: LayoutDashboard,
  admin: Shield,
  hr: Users,
  reports: BarChart3,
  communication: MessageSquare,
  workflow: GitBranch,
  system: Settings,
  support: HelpCircle,
};
